image: zacksleo/docker-composer:alpine

before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" > ~/deploy.key
    - chmod 0600 ~/deploy.key
    - ssh-add ~/deploy.key
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
    stage: deploy
    variables:
        DEPLOY_SERVER: "139.198.9.76"
    script:
        - rm -rf .git/
        - rsync -rtvhze ssh . root@$DEPLOY_SERVER:/mnt/data/$CI_PROJECT_NAME --stats
        - ssh root@$DEPLOY_SERVER "export COMPOSE_HTTP_TIMEOUT=120 && export DOCKER_CLIENT_TIMEOUT=120 && cd /mnt/data/$CI_PROJECT_NAME && docker-compose stop && docker-compose rm -f && docker-compose up -d --build"
        - ssh root@$DEPLOY_SERVER "docker exec -i $CI_PROJECT_NAME oauth2_proxy -config /etc/oauth2_proxy.cfg &>/dev/null&"
