version: '2'
services:

   gollum:
       build: ./
       expose:
           - "80"
       volumes:
           - ./wiki/:/wiki
          #- ./nginx/oauth2_proxy.cfg:/etc/oauth2_proxy.cfg
   nginx:
        container_name: gollum
        build: ./nginx
        ports:
            - "443:443"
        links:
            - gollum
        volumes_from:
            - gollum