version: '2'
services:

   gollum:
       build: ./
       expose:
           - "80"
       volumes:
           - ./wiki/:/wiki
   nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - gollum
        volumes_from:
            - gollum